[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[phases.setup]
cmds = ["cp Caddyfile /assets/Caddyfile"]

[start]
cmd = "caddy run --config /assets/Caddyfile"
